stages:
  - build
  - test
  - publish

build:
  stage: build
  only:
    - merge_requests
  image: php:8.0
  artifacts:
    paths:
      - dev
      - prod
    expire_in: 1 hour
  before_script:
    - bash .ci/docker_install.sh > /dev/null
  script:
    - bash .ci/build_prepare_dir.sh > /dev/null
    - cp -r build dev
    - cp -r build prod
    - cd ./dev && make dev && bash ../.ci/build_clean_dir.sh && cd ..
    - cd ./prod && make prod && bash ../.ci/build_clean_dir.sh && cd ..

test:phpstan:
  stage: test
  needs: ['build']
  only:
    - merge_requests
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '8.0'
  artifacts:
    paths:
      - dev
  script:
    - cp -r dev /var/www/html/custom/plugins/ElioFactFinder
    - cd /var/www/html/custom/plugins/ElioFactFinder
    - make stan

test:php8.0:
  stage: test
  needs: ['build']
  only:
    - merge_requests
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '8.0'
  artifacts:
    paths:
      - dev
  script:
    - bash .ci/test_phpunit.sh

test:php7.4:
  stage: test
  needs: ['build']
  only:
    - merge_requests
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '7.4'
  artifacts:
    paths:
      - dev
  script:
    - bash .ci/test_phpunit.sh

publish:
  image: curlimages/curl:latest
  stage: publish
  needs: ['build']
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    # Output state information
    - if [ $code -eq 201 ]; then
      echo "Package created - Code $code - $body";
      else
      echo "Could not create package - Code $code - $body";
      exit 1;
      fi
