stages:
  - build
  - test
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/release"

build:
  stage: build
  only:
    - merge_requests
    - tags
  image: php:8.0
  artifacts:
    paths: ["dev", "prod", "build"]
    expire_in: 1 hour
  before_script:
    - bash .gitlab/scripts/composer_install.sh > /dev/null
  script:
    - bash .gitlab/scripts/build_prepare_dir.sh > /dev/null
    - cp -r ./prepare ./build/dev
    - cd ./build/dev && ls -la && make dev && bash ../../.gitlab/scripts/build_clean_dir.sh && cd ../../

    - cp -r ./prepare ./build/prod
    - cd ./build/dev && make dev && bash ../../.gitlab/scripts/build_clean_dir.sh && cd ..
    - cd ./build/prod && make prod && bash ../../.gitlab/scripts/build_clean_dir.sh && cd ..
    - zip -r ./build/dev.zip ./build/dev
    - zip -r ./build/prod.zip ./build/prod

test:phpstan:
  stage: test
  needs: ['build']
  only:
    - merge_requests
    - tags
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '8.0'
  artifacts:
    paths:
      - dev
      - "./phpstan-report.json"
    when: always
    reports:
      codequality: phpstan-report.json
  script:
    - ls -la
    - cp -r dev /var/www/html/custom/plugins/ElioFactFinder
    - cd /var/www/html/custom/plugins/ElioFactFinder
    - make stan-gitlab
    - cp phpstan-report.json /var/www/html/phpstan-report.json
    - ls -la
    - cd /var/www/html/
    - ls -la

#test:php8.0:
#  stage: test
#  needs: ['build']
#  only:
#    - merge_requests
#    - tags
#  image: dockware/dev:latest
#  variables:
#    PHP_VERSION: '8.0'
#  artifacts:
#    paths:
#      - dev
#  script:
#    - bash .gitlab/scripts/test_phpunit.sh
#
#test:php7.4:
#  stage: test
#  needs: ['build']
#  only:
#    - merge_requests
#    - tags
#  image: dockware/dev:latest
#  variables:
#    PHP_VERSION: '7.4'
#  artifacts:
#    paths:
#      - dev
#  script:
#    - bash .gitlab/scripts/test_phpunit.sh

upload:
  stage: release
#  needs: ['test:phpstan', 'test:php7.4', 'test:php8.0']
  needs: ['build']
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - build
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./build/prod.zip "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/prod.zip"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./build/dev.zip "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/dev.zip"

release_create:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION must be defined
    tag_name: '$CI_COMMIT_TAG'                                       # elsewhere in the pipeline.
    ref: '$CI_COMMIT_TAG'
    assets: # Optional, multiple asset links
      links:
        - name: 'prod.zip'
          url: '${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/prod.zip'
        - name: 'dev.zip'
          url: '${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/dev.zip'