#include:
#  - local: .gitlab/ci/test.yml
##  - local: .gitlab/ci/analyze.yml
#  - local: .gitlab/ci/build.yml
##  - local: .gitlab/ci/publish.yml
##  - local: .gitlab/ci/analyze-container.yml
##  - local: .gitlab/ci/release.yml


stages:
  - build
  - test
  - release

build:
  stage: build
  only:
    - merge_requests
    - tags
  image: php:8.0
  artifacts:
    paths:
      - dev
      - prod
    expire_in: 1 hour
  before_script:
    - bash .gitlab/scripts/docker_install.sh > /dev/null
  script:
    - bash .gitlab/scripts/build_prepare_dir.sh > /dev/null
    - cp -r build dev
    - cp -r build prod
    - cd ./dev && make dev && bash ../.gitlab/scripts/build_clean_dir.sh && cd ..
    - cd ./prod && make prod && bash ../.gitlab/scripts/build_clean_dir.sh && cd ..

test:phpstan:
  stage: test
  needs: ['build']
  only:
    - merge_requests
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '8.0'
  artifacts:
    paths:
      - dev
  script:
    - cp -r dev /var/www/html/custom/plugins/ElioFactFinder
    - cd /var/www/html/custom/plugins/ElioFactFinder
    - make stan

test:php8.0:
  stage: test
  needs: ['build']
  only:
    - merge_requests
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '8.0'
  artifacts:
    paths:
      - dev
  script:
    - bash .gitlab/scripts/test_phpunit.sh

test:php7.4:
  stage: test
  needs: ['build']
  only:
    - merge_requests
  image: dockware/dev:latest
  variables:
    PHP_VERSION: '7.4'
  artifacts:
    paths:
      - dev
  script:
    - bash .gitlab/scripts/test_phpunit.sh

release_job:
  stage: release
  needs: ['build']
  only:
    - tags
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Running the release job."
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
    assets:
      links:
        - name: 'asset1'
          url: 'https://example.com/assets/1'
        - name: 'asset2'
          url: 'https://example.com/assets/2'
          filepath: '/pretty/url/1' # optional
          link_type: 'other' # optional
